export const GET_ALL_ERRORS = "GET_ALL_ERRORS";
export const SIGN_UP_USER = "SIGN_UP_USER";
export const IS_LOADING = "IS_LOADING";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOAD_USER_PROFILE_SUCCESS = "LOAD_USER_PROFILE_SUCCESS";
export const PROGRESS_UPDATE_SUCCESS = "PROGRESS_UPDATE_SUCCESS";
export const UPLOAD_DATA_SUCCESS = "UPLOAD_DATA_SUCCESS";
export const GET_ALL_UPLOAD_SUCCESS = "GET_ALL_UPLOAD_SUCCESS";